import type { Config } from 'tailwindcss';

export default {
    content: ['./index.html', './src/**/*.{ts,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: '#1a365d',
                'tertiary-container': '#003f25',
                'surface-dim': '#d7dadc',
                'inverse-primary': '#adc7f7',
                'error-container': '#ffdad6',
                'surface-container-highest': '#e0e3e5',
                'secondary-fixed-dim': '#bdc7dc',
                'on-primary': '#ffffff',
                'on-secondary-fixed-variant': '#3d4759',
                'tertiary-fixed-dim': '#83d8a6',
                'surface-container-high': '#e5e9eb',
                'on-tertiary-container': '#5caf81',
                'on-surface': '#181c1e',
                surface: '#f7fafc',
                'primary-container': '#1a365d',
                'surface-bright': '#f7fafc',
                'on-secondary-fixed': '#121c2c',
                'on-error': '#ffffff',
                'on-tertiary-fixed-variant': '#005231',
                'on-tertiary': '#ffffff',
                'secondary-container': '#d6e0f6',
                'on-secondary-container': '#596376',
                'primary-fixed-dim': '#adc7f7',
                'tertiary-fixed': '#9ff5c1',
                tertiary: '#2f855a',
                'surface-container-lowest': '#ffffff',
                'on-secondary': '#ffffff',
                background: '#f7fafc',
                'on-primary-container': '#86a0cd',
                'inverse-on-surface': '#eef1f3',
                'surface-tint': '#455f88',
                'surface-container': '#ebeef0',
                'outline-variant': '#c4c6cf',
                'on-primary-fixed-variant': '#2d476f',
                'on-error-container': '#93000a',
                'on-primary-fixed': '#001b3c',
                secondary: '#555f71',
                'inverse-surface': '#2d3133',
                outline: '#74777f',
                'on-surface-variant': '#43474e',
                error: '#ba1a1a',
                'primary-fixed': '#d6e3ff',
                'surface-container-low': '#f1f4f6',
                'on-tertiary-fixed': '#002111',
                'secondary-fixed': '#d9e3f9',
                'surface-variant': '#e0e3e5',
                'on-background': '#181c1e',
                info: '#cfb000',
                success: '#017949',
                warning: '#b15102',
            },
            fontFamily: {
                headline: ['Inter'],
                body: ['Inter'],
                label: ['Inter'],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontSize: {
                'h1-display-jp': [
                    '32px',
                    {
                        lineHeight: '1.4',
                        letterSpacing: '-0.02em',
                        fontWeight: '700',
                    },
                ],
                'data-tabular': [
                    '14px',
                    {
                        lineHeight: '1.2',
                        letterSpacing: '0.05em',
                        fontWeight: '500',
                    },
                ],
                'body-sm-jp': [
                    '14px',
                    {
                        lineHeight: '1.6',
                        letterSpacing: '0.01em',
                        fontWeight: '400',
                    },
                ],
                'label-caps': [
                    '12px',
                    {
                        lineHeight: '1.2',
                        letterSpacing: '0.08em',
                        fontWeight: '700',
                    },
                ],
                'body-md-jp': [
                    '16px',
                    {
                        lineHeight: '1.7',
                        letterSpacing: '0.02em',
                        fontWeight: '400',
                    },
                ],
                'h3-section-jp': [
                    '18px',
                    {
                        lineHeight: '1.5',
                        letterSpacing: '0em',
                        fontWeight: '700',
                    },
                ],
                'h2-header-jp': [
                    '24px',
                    {
                        lineHeight: '1.5',
                        letterSpacing: '-0.01em',
                        fontWeight: '700',
                    },
                ],
                'h1-mobile': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
            },
        },
    },
    plugins: [],
} satisfies Config;
